//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profitocracy.Mobile.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_sr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_sr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Profitocracy.Mobile.Resources.Strings.AppResources.sr", typeof(AppResources_sr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назив категорије.
        /// </summary>
        internal static string AddCategory_CategoryName {
            get {
                return ResourceManager.GetString("AddCategory_CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Планирани износ.
        /// </summary>
        internal static string AddCategory_PlannedAmount {
            get {
                return ResourceManager.GetString("AddCategory_PlannedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сачувај категорију.
        /// </summary>
        internal static string AddCategory_SaveCategory {
            get {
                return ResourceManager.GetString("AddCategory_SaveCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наведи планирани износ.
        /// </summary>
        internal static string AddCategory_SpecifyPlannedAmount {
            get {
                return ResourceManager.GetString("AddCategory_SpecifyPlannedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Износ у основној валути.
        /// </summary>
        internal static string AddTransaction_Amount {
            get {
                return ResourceManager.GetString("AddTransaction_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категорија.
        /// </summary>
        internal static string AddTransaction_Category {
            get {
                return ResourceManager.GetString("AddTransaction_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Датум.
        /// </summary>
        internal static string AddTransaction_Date {
            get {
                return ResourceManager.GetString("AddTransaction_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опис.
        /// </summary>
        internal static string AddTransaction_Description {
            get {
                return ResourceManager.GetString("AddTransaction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расход.
        /// </summary>
        internal static string AddTransaction_Expense {
            get {
                return ResourceManager.GetString("AddTransaction_Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приход.
        /// </summary>
        internal static string AddTransaction_Income {
            get {
                return ResourceManager.GetString("AddTransaction_Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главни.
        /// </summary>
        internal static string AddTransaction_Main {
            get {
                return ResourceManager.GetString("AddTransaction_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мултивалутна трансакција.
        /// </summary>
        internal static string AddTransaction_MultiCurrencyTransaction {
            get {
                return ResourceManager.GetString("AddTransaction_MultiCurrencyTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Без категорије.
        /// </summary>
        internal static string AddTransaction_NoneCategory {
            get {
                return ResourceManager.GetString("AddTransaction_NoneCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Износ у оригиналној валути.
        /// </summary>
        internal static string AddTransaction_OriginalCurrencyAmount {
            get {
                return ResourceManager.GetString("AddTransaction_OriginalCurrencyAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Понављајућа трансакција.
        /// </summary>
        internal static string AddTransaction_RecurringTransaction {
            get {
                return ResourceManager.GetString("AddTransaction_RecurringTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профитократија аутоматски креира трансакције за ваше понављајуће трансакције у позадини и жели да вас обавести о њима.
        /// </summary>
        internal static string AddTransaction_RecurringTransaction_PostNotificationAlert_Message {
            get {
                return ResourceManager.GetString("AddTransaction_RecurringTransaction_PostNotificationAlert_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        internal static string AddTransaction_RecurringTransaction_PostNotificationAlert_Ok {
            get {
                return ResourceManager.GetString("AddTransaction_RecurringTransaction_PostNotificationAlert_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обавештење о понављајућим трансакцијама.
        /// </summary>
        internal static string AddTransaction_RecurringTransaction_PostNotificationAlert_Title {
            get {
                return ResourceManager.GetString("AddTransaction_RecurringTransaction_PostNotificationAlert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Интервал понављајућих трансакција.
        /// </summary>
        internal static string AddTransaction_RecurringTransactionInterval {
            get {
                return ResourceManager.GetString("AddTransaction_RecurringTransactionInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сачувани.
        /// </summary>
        internal static string AddTransaction_Saved {
            get {
                return ResourceManager.GetString("AddTransaction_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сачувај трансакцију.
        /// </summary>
        internal static string AddTransaction_SaveTransaction {
            get {
                return ResourceManager.GetString("AddTransaction_SaveTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Споредни.
        /// </summary>
        internal static string AddTransaction_Secondary {
            get {
                return ResourceManager.GetString("AddTransaction_Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Износ за исплату.
        /// </summary>
        internal static string AddTransaction_WithdrawAmount {
            get {
                return ResourceManager.GetString("AddTransaction_WithdrawAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исплата са сачуваних средстава.
        /// </summary>
        internal static string AddTransaction_WithdrawSavedFunds {
            get {
                return ResourceManager.GetString("AddTransaction_WithdrawSavedFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хајде да користимо биометрију да вас аутентификујемо.
        /// </summary>
        internal static string Auth_Biometric_Description {
            get {
                return ResourceManager.GetString("Auth_Biometric_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аутентификација није успела.
        /// </summary>
        internal static string Auth_Biometric_NegativeText {
            get {
                return ResourceManager.GetString("Auth_Biometric_NegativeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коришћење биометрије за аутентификацију.
        /// </summary>
        internal static string Auth_Biometric_Subtitle {
            get {
                return ResourceManager.GetString("Auth_Biometric_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аутентификација.
        /// </summary>
        internal static string Auth_Biometric_Title {
            get {
                return ResourceManager.GetString("Auth_Biometric_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Биометријска аутентификација није успела.
        /// </summary>
        internal static string Auth_InvalidBiometricAlert_Description {
            get {
                return ResourceManager.GetString("Auth_InvalidBiometricAlert_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У реду.
        /// </summary>
        internal static string Auth_InvalidBiometricAlert_Ok {
            get {
                return ResourceManager.GetString("Auth_InvalidBiometricAlert_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аутентификација није успела.
        /// </summary>
        internal static string Auth_InvalidBiometricAlert_Title {
            get {
                return ResourceManager.GetString("Auth_InvalidBiometricAlert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лозинка није валидна.
        /// </summary>
        internal static string Auth_InvalidPasswordAlert_Description {
            get {
                return ResourceManager.GetString("Auth_InvalidPasswordAlert_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Покушајте поново.
        /// </summary>
        internal static string Auth_InvalidPasswordAlert_Ok {
            get {
                return ResourceManager.GetString("Auth_InvalidPasswordAlert_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аутентификација није успела.
        /// </summary>
        internal static string Auth_InvalidPasswordAlert_Title {
            get {
                return ResourceManager.GetString("Auth_InvalidPasswordAlert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добродошли у Profitocracy.
        /// </summary>
        internal static string Auth_Welcome {
            get {
                return ResourceManager.GetString("Auth_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аутентификација.
        /// </summary>
        internal static string AuthSettings_Authentication {
            get {
                return ResourceManager.GetString("AuthSettings_Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Биометрија није подржана на вашем уређају.
        /// </summary>
        internal static string AuthSettings_BiometricNotSupported {
            get {
                return ResourceManager.GetString("AuthSettings_BiometricNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Омогућено.
        /// </summary>
        internal static string AuthSettings_Enabled {
            get {
                return ResourceManager.GetString("AuthSettings_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шифра треба да садржи само 4 цифре.
        /// </summary>
        internal static string AuthSettings_Error_PassCodeFormat {
            get {
                return ResourceManager.GetString("AuthSettings_Error_PassCodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опште.
        /// </summary>
        internal static string AuthSettings_General {
            get {
                return ResourceManager.GetString("AuthSettings_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шифра.
        /// </summary>
        internal static string AuthSettings_PassCode {
            get {
                return ResourceManager.GetString("AuthSettings_PassCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сачувај подешавања.
        /// </summary>
        internal static string AuthSettings_Save {
            get {
                return ResourceManager.GetString("AuthSettings_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подешавања аутентификације су успешно сачувана..
        /// </summary>
        internal static string AuthSettings_SavedAlert_Description {
            get {
                return ResourceManager.GetString("AuthSettings_SavedAlert_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У реду.
        /// </summary>
        internal static string AuthSettings_SavedAlert_Ok {
            get {
                return ResourceManager.GetString("AuthSettings_SavedAlert_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успех.
        /// </summary>
        internal static string AuthSettings_SavedAlert_Title {
            get {
                return ResourceManager.GetString("AuthSettings_SavedAlert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Биометрија (FaceID, Отисак прста).
        /// </summary>
        internal static string AuthSettings_UseBiometrics {
            get {
                return ResourceManager.GetString("AuthSettings_UseBiometrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Без ограничења.
        /// </summary>
        internal static string Categories_NoLimits {
            get {
                return ResourceManager.GetString("Categories_NoLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Откажи.
        /// </summary>
        internal static string CategoriesSettings_DeleteAlert_Cancel {
            get {
                return ResourceManager.GetString("CategoriesSettings_DeleteAlert_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да ли сте сигурни да желите да обришете категорију &quot;{0}&quot;?.
        /// </summary>
        internal static string CategoriesSettings_DeleteAlert_Description {
            get {
                return ResourceManager.GetString("CategoriesSettings_DeleteAlert_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        internal static string CategoriesSettings_DeleteAlert_Ok {
            get {
                return ResourceManager.GetString("CategoriesSettings_DeleteAlert_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Брисање категорије.
        /// </summary>
        internal static string CategoriesSettings_DeleteAlert_Title {
            get {
                return ResourceManager.GetString("CategoriesSettings_DeleteAlert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Износ мора бити број.
        /// </summary>
        internal static string CommonError_AmountNumber {
            get {
                return ResourceManager.GetString("CommonError_AmountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стање мора бити број.
        /// </summary>
        internal static string CommonError_BalanceNumber {
            get {
                return ResourceManager.GetString("CommonError_BalanceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нема података за извоз.
        /// </summary>
        internal static string CommonError_ExportDataIsEmpty {
            get {
                return ResourceManager.GetString("CommonError_ExportDataIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу да пронађем категорију за брисање.
        /// </summary>
        internal static string CommonError_FindCategoryToDelete {
            get {
                return ResourceManager.GetString("CommonError_FindCategoryToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу да пронађем категорију за измену.
        /// </summary>
        internal static string CommonError_FindCategoryToEdit {
            get {
                return ResourceManager.GetString("CommonError_FindCategoryToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу да пронађем трансакцију за брисање.
        /// </summary>
        internal static string CommonError_FindTransactionToDelete {
            get {
                return ResourceManager.GetString("CommonError_FindTransactionToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу да пронађем трансакцију за измену.
        /// </summary>
        internal static string CommonError_FindTransactionToEdit {
            get {
                return ResourceManager.GetString("CommonError_FindTransactionToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу да добавим информације о категорији.
        /// </summary>
        internal static string CommonError_GetCategoryInfo {
            get {
                return ResourceManager.GetString("CommonError_GetCategoryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу да добавим тренутни профил.
        /// </summary>
        internal static string CommonError_GetCurrentProfile {
            get {
                return ResourceManager.GetString("CommonError_GetCurrentProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу да пронађем профил са наведеним ID-ом.
        /// </summary>
        internal static string CommonError_GetProfileById {
            get {
                return ResourceManager.GetString("CommonError_GetProfileById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу да пронађем подешавања.
        /// </summary>
        internal static string CommonError_GetSettings {
            get {
                return ResourceManager.GetString("CommonError_GetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дошло је до интерне грешке. Покушајте поново.
        /// </summary>
        internal static string CommonError_InternalErrorTryAgain {
            get {
                return ResourceManager.GetString("CommonError_InternalErrorTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нема података за увоз.
        /// </summary>
        internal static string CommonError_NoDataToImport {
            get {
                return ResourceManager.GetString("CommonError_NoDataToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу да отворим страницу за додавање категорије.
        /// </summary>
        internal static string CommonError_OpenAddCategoryPage {
            get {
                return ResourceManager.GetString("CommonError_OpenAddCategoryPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу да отворим страницу за измену трансакције.
        /// </summary>
        internal static string CommonError_OpenEditTransactionPage {
            get {
                return ResourceManager.GetString("CommonError_OpenEditTransactionPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу да отворим страницу нови период.
        /// </summary>
        internal static string CommonError_OpenNewPeriodPage {
            get {
                return ResourceManager.GetString("CommonError_OpenNewPeriodPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу да отворим страницу са филтерима прегледа.
        /// </summary>
        internal static string CommonError_OpenOverviewFiltersPage {
            get {
                return ResourceManager.GetString("CommonError_OpenOverviewFiltersPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу да отворим страницу са филтерима трансакција.
        /// </summary>
        internal static string CommonError_OpenTransactionsFiltersPage {
            get {
                return ResourceManager.GetString("CommonError_OpenTransactionsFiltersPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Износ у оригиналној валути мора бити број.
        /// </summary>
        internal static string CommonError_OriginalCurrencyAmountNumber {
            get {
                return ResourceManager.GetString("CommonError_OriginalCurrencyAmountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Планирани износ мора бити број.
        /// </summary>
        internal static string CommonError_PlannedAmountNumber {
            get {
                return ResourceManager.GetString("CommonError_PlannedAmountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу да прикажем филтриране трансакције.
        /// </summary>
        internal static string CommonError_ShowFilteredTransactions {
            get {
                return ResourceManager.GetString("CommonError_ShowFilteredTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неважећи тип трансакције.
        /// </summary>
        internal static string CommonError_TransactionType {
            get {
                return ResourceManager.GetString("CommonError_TransactionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неподржани тип датотеке.
        /// </summary>
        internal static string CommonError_WrongFileExtension {
            get {
                return ResourceManager.GetString("CommonError_WrongFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to УАЕ дирхам.
        /// </summary>
        internal static string Currencies_AED {
            get {
                return ResourceManager.GetString("Currencies_AED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аргентински пезос.
        /// </summary>
        internal static string Currencies_ARS {
            get {
                return ResourceManager.GetString("Currencies_ARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аустралијски долар.
        /// </summary>
        internal static string Currencies_AUD {
            get {
                return ResourceManager.GetString("Currencies_AUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бангладешка така.
        /// </summary>
        internal static string Currencies_BDT {
            get {
                return ResourceManager.GetString("Currencies_BDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бугарски лев.
        /// </summary>
        internal static string Currencies_BGN {
            get {
                return ResourceManager.GetString("Currencies_BGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бразилски реал.
        /// </summary>
        internal static string Currencies_BRL {
            get {
                return ResourceManager.GetString("Currencies_BRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Биткоин.
        /// </summary>
        internal static string Currencies_BTC {
            get {
                return ResourceManager.GetString("Currencies_BTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Канадски долар.
        /// </summary>
        internal static string Currencies_CAD {
            get {
                return ResourceManager.GetString("Currencies_CAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Швајцарски франак.
        /// </summary>
        internal static string Currencies_CHF {
            get {
                return ResourceManager.GetString("Currencies_CHF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чилеански пезос.
        /// </summary>
        internal static string Currencies_CLP {
            get {
                return ResourceManager.GetString("Currencies_CLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кинески јуан.
        /// </summary>
        internal static string Currencies_CNY {
            get {
                return ResourceManager.GetString("Currencies_CNY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Колумбијски пезос.
        /// </summary>
        internal static string Currencies_COP {
            get {
                return ResourceManager.GetString("Currencies_COP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чешка круна.
        /// </summary>
        internal static string Currencies_CZK {
            get {
                return ResourceManager.GetString("Currencies_CZK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данска круна.
        /// </summary>
        internal static string Currencies_DKK {
            get {
                return ResourceManager.GetString("Currencies_DKK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Египатска фунта.
        /// </summary>
        internal static string Currencies_EGP {
            get {
                return ResourceManager.GetString("Currencies_EGP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Етер.
        /// </summary>
        internal static string Currencies_ETH {
            get {
                return ResourceManager.GetString("Currencies_ETH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Евро.
        /// </summary>
        internal static string Currencies_EUR {
            get {
                return ResourceManager.GetString("Currencies_EUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фиџи долар.
        /// </summary>
        internal static string Currencies_FJD {
            get {
                return ResourceManager.GetString("Currencies_FJD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Британска фунта.
        /// </summary>
        internal static string Currencies_GBP {
            get {
                return ResourceManager.GetString("Currencies_GBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гански седи.
        /// </summary>
        internal static string Currencies_GHS {
            get {
                return ResourceManager.GetString("Currencies_GHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хонгконшки долар.
        /// </summary>
        internal static string Currencies_HKD {
            get {
                return ResourceManager.GetString("Currencies_HKD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мађарска форинта.
        /// </summary>
        internal static string Currencies_HUF {
            get {
                return ResourceManager.GetString("Currencies_HUF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Индонежанска рупија.
        /// </summary>
        internal static string Currencies_IDR {
            get {
                return ResourceManager.GetString("Currencies_IDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Израелски нови шекел.
        /// </summary>
        internal static string Currencies_ILS {
            get {
                return ResourceManager.GetString("Currencies_ILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Индијска рупија.
        /// </summary>
        internal static string Currencies_INR {
            get {
                return ResourceManager.GetString("Currencies_INR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ирачки динар.
        /// </summary>
        internal static string Currencies_IQD {
            get {
                return ResourceManager.GetString("Currencies_IQD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Јапански јен.
        /// </summary>
        internal static string Currencies_JPY {
            get {
                return ResourceManager.GetString("Currencies_JPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кенијски шилинг.
        /// </summary>
        internal static string Currencies_KES {
            get {
                return ResourceManager.GetString("Currencies_KES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Јужнокорејски вон.
        /// </summary>
        internal static string Currencies_KRW {
            get {
                return ResourceManager.GetString("Currencies_KRW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кувајтски динар.
        /// </summary>
        internal static string Currencies_KWD {
            get {
                return ResourceManager.GetString("Currencies_KWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мексички пезос.
        /// </summary>
        internal static string Currencies_MXN {
            get {
                return ResourceManager.GetString("Currencies_MXN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Малезијски рингит.
        /// </summary>
        internal static string Currencies_MYR {
            get {
                return ResourceManager.GetString("Currencies_MYR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нигеријска наира.
        /// </summary>
        internal static string Currencies_NGN {
            get {
                return ResourceManager.GetString("Currencies_NGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Норвешка круна.
        /// </summary>
        internal static string Currencies_NOK {
            get {
                return ResourceManager.GetString("Currencies_NOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новозеландски долар.
        /// </summary>
        internal static string Currencies_NZD {
            get {
                return ResourceManager.GetString("Currencies_NZD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Омански ријал.
        /// </summary>
        internal static string Currencies_OMR {
            get {
                return ResourceManager.GetString("Currencies_OMR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Филипински пезос.
        /// </summary>
        internal static string Currencies_PHP {
            get {
                return ResourceManager.GetString("Currencies_PHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пакистанска рупија.
        /// </summary>
        internal static string Currencies_PKR {
            get {
                return ResourceManager.GetString("Currencies_PKR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пољски злот.
        /// </summary>
        internal static string Currencies_PLN {
            get {
                return ResourceManager.GetString("Currencies_PLN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Парагвајски гварани.
        /// </summary>
        internal static string Currencies_PYG {
            get {
                return ResourceManager.GetString("Currencies_PYG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Румунски леј.
        /// </summary>
        internal static string Currencies_RON {
            get {
                return ResourceManager.GetString("Currencies_RON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Српски динар.
        /// </summary>
        internal static string Currencies_RSD {
            get {
                return ResourceManager.GetString("Currencies_RSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Руска рубља.
        /// </summary>
        internal static string Currencies_RUB {
            get {
                return ResourceManager.GetString("Currencies_RUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Саудијски ријал.
        /// </summary>
        internal static string Currencies_SAR {
            get {
                return ResourceManager.GetString("Currencies_SAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шведска круна.
        /// </summary>
        internal static string Currencies_SEK {
            get {
                return ResourceManager.GetString("Currencies_SEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сингапурски долар.
        /// </summary>
        internal static string Currencies_SGD {
            get {
                return ResourceManager.GetString("Currencies_SGD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тајландски бат.
        /// </summary>
        internal static string Currencies_THB {
            get {
                return ResourceManager.GetString("Currencies_THB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Турска лира.
        /// </summary>
        internal static string Currencies_TRY {
            get {
                return ResourceManager.GetString("Currencies_TRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тајвански долар.
        /// </summary>
        internal static string Currencies_TWD {
            get {
                return ResourceManager.GetString("Currencies_TWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Амерички долар.
        /// </summary>
        internal static string Currencies_USD {
            get {
                return ResourceManager.GetString("Currencies_USD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Венецуелански боливар.
        /// </summary>
        internal static string Currencies_VEF {
            get {
                return ResourceManager.GetString("Currencies_VEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вијетнамски донг.
        /// </summary>
        internal static string Currencies_VND {
            get {
                return ResourceManager.GetString("Currencies_VND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Самоанска тала.
        /// </summary>
        internal static string Currencies_WST {
            get {
                return ResourceManager.GetString("Currencies_WST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Јужноафрички ранд.
        /// </summary>
        internal static string Currencies_ZAR {
            get {
                return ResourceManager.GetString("Currencies_ZAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почетно стање.
        /// </summary>
        internal static string EditProfile_InitialBalance {
            get {
                return ResourceManager.GetString("EditProfile_InitialBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профил.
        /// </summary>
        internal static string EditProfile_Profile {
            get {
                return ResourceManager.GetString("EditProfile_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назив профила.
        /// </summary>
        internal static string EditProfile_ProfileName {
            get {
                return ResourceManager.GetString("EditProfile_ProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сачувај профил.
        /// </summary>
        internal static string EditProfile_SaveProfile {
            get {
                return ResourceManager.GetString("EditProfile_SaveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дошло је до грешке.
        /// </summary>
        internal static string ErrorAlert_Description {
            get {
                return ResourceManager.GetString("ErrorAlert_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У реду.
        /// </summary>
        internal static string ErrorAlert_Ok {
            get {
                return ResourceManager.GetString("ErrorAlert_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грешка.
        /// </summary>
        internal static string ErrorAlert_Title {
            get {
                return ResourceManager.GetString("ErrorAlert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стање.
        /// </summary>
        internal static string Home_Balance {
            get {
                return ResourceManager.GetString("Home_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трошкови по категоријама.
        /// </summary>
        internal static string Home_Categories {
            get {
                return ResourceManager.GetString("Home_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дневни износи.
        /// </summary>
        internal static string Home_DailyAmounts {
            get {
                return ResourceManager.GetString("Home_DailyAmounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главни.
        /// </summary>
        internal static string Home_Main {
            get {
                return ResourceManager.GetString("Home_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нема категорија.
        /// </summary>
        internal static string Home_NoCategories {
            get {
                return ResourceManager.GetString("Home_NoCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сачувани.
        /// </summary>
        internal static string Home_Saved {
            get {
                return ResourceManager.GetString("Home_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сачувани износи.
        /// </summary>
        internal static string Home_SavedAmounts {
            get {
                return ResourceManager.GetString("Home_SavedAmounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Споредни.
        /// </summary>
        internal static string Home_Secondary {
            get {
                return ResourceManager.GetString("Home_Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Типови трошења.
        /// </summary>
        internal static string Home_SpendingTypes {
            get {
                return ResourceManager.GetString("Home_SpendingTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почни нови период.
        /// </summary>
        internal static string Home_StartNewPeriod {
            get {
                return ResourceManager.GetString("Home_StartNewPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данас.
        /// </summary>
        internal static string Home_TodayBalance {
            get {
                return ResourceManager.GetString("Home_TodayBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сутра.
        /// </summary>
        internal static string Home_TomorrowBalance {
            get {
                return ResourceManager.GetString("Home_TomorrowBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изаберите датотеку.
        /// </summary>
        internal static string ImportExport_ChooseFile {
            get {
                return ResourceManager.GetString("ImportExport_ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Извоз.
        /// </summary>
        internal static string ImportExport_Export {
            get {
                return ResourceManager.GetString("ImportExport_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Извоз категорија.
        /// </summary>
        internal static string ImportExport_ExportCategories {
            get {
                return ResourceManager.GetString("ImportExport_ExportCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Извоз у датотеку.
        /// </summary>
        internal static string ImportExport_ExportFile {
            get {
                return ResourceManager.GetString("ImportExport_ExportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Извоз профила.
        /// </summary>
        internal static string ImportExport_ExportProfiles {
            get {
                return ResourceManager.GetString("ImportExport_ExportProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Извоз трансакција.
        /// </summary>
        internal static string ImportExport_ExportTransactions {
            get {
                return ResourceManager.GetString("ImportExport_ExportTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увоз.
        /// </summary>
        internal static string ImportExport_Import {
            get {
                return ResourceManager.GetString("ImportExport_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изаберите Profitocracy резервну датотеку.
        /// </summary>
        internal static string ImportExport_SelectBackupFile {
            get {
                return ResourceManager.GetString("ImportExport_SelectBackupFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подаци су успешно извезени.
        /// </summary>
        internal static string ImportExport_SuccessExportAlert_Description {
            get {
                return ResourceManager.GetString("ImportExport_SuccessExportAlert_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У реду.
        /// </summary>
        internal static string ImportExport_SuccessExportAlert_Ok {
            get {
                return ResourceManager.GetString("ImportExport_SuccessExportAlert_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успех.
        /// </summary>
        internal static string ImportExport_SuccessExportAlert_Title {
            get {
                return ResourceManager.GetString("ImportExport_SuccessExportAlert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подаци су успешно увезени.
        /// </summary>
        internal static string ImportExport_SuccessImportAlert_Description {
            get {
                return ResourceManager.GetString("ImportExport_SuccessImportAlert_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У реду.
        /// </summary>
        internal static string ImportExport_SuccessImportAlert_Ok {
            get {
                return ResourceManager.GetString("ImportExport_SuccessImportAlert_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успех.
        /// </summary>
        internal static string ImportExport_SuccessImportAlert_Title {
            get {
                return ResourceManager.GetString("ImportExport_SuccessImportAlert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да би промене ступиле на снагу, потребно је поново покренути апликацију..
        /// </summary>
        internal static string InfoAlert_ChangeLanguage_Message {
            get {
                return ResourceManager.GetString("InfoAlert_ChangeLanguage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У реду.
        /// </summary>
        internal static string InfoAlert_ChangeLanguage_Ok {
            get {
                return ResourceManager.GetString("InfoAlert_ChangeLanguage_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Упозорење.
        /// </summary>
        internal static string InfoAlert_ChangeLanguage_Title {
            get {
                return ResourceManager.GetString("InfoAlert_ChangeLanguage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ова функција још увек није доступна. Ускоро ћемо је имплементирати.
        /// </summary>
        internal static string InfoAlert_FeatureNotAvailable_Message {
            get {
                return ResourceManager.GetString("InfoAlert_FeatureNotAvailable_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У реду.
        /// </summary>
        internal static string InfoAlert_FeatureNotAvailable_Ok {
            get {
                return ResourceManager.GetString("InfoAlert_FeatureNotAvailable_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Још увек није доступно.
        /// </summary>
        internal static string InfoAlert_FeatureNotAvailable_Title {
            get {
                return ResourceManager.GetString("InfoAlert_FeatureNotAvailable_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Languages_English {
            get {
                return ResourceManager.GetString("Languages_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        internal static string Languages_French {
            get {
                return ResourceManager.GetString("Languages_French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch.
        /// </summary>
        internal static string Languages_German {
            get {
                return ResourceManager.GetString("Languages_German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        internal static string Languages_Russian {
            get {
                return ResourceManager.GetString("Languages_Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Српски (ћирилица).
        /// </summary>
        internal static string Languages_SerbianCyrillic {
            get {
                return ResourceManager.GetString("Languages_SerbianCyrillic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Srpski (latinica).
        /// </summary>
        internal static string Languages_SerbianLatin {
            get {
                return ResourceManager.GetString("Languages_SerbianLatin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        internal static string Languages_Spanish {
            get {
                return ResourceManager.GetString("Languages_Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трошкови по категоријама.
        /// </summary>
        internal static string Overview_CategoriesExpenses {
            get {
                return ResourceManager.GetString("Overview_CategoriesExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Планирани и стварни трошкови по категоријама.
        /// </summary>
        internal static string Overview_CategoriesPlannedAndActual {
            get {
                return ResourceManager.GetString("Overview_CategoriesPlannedAndActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дневни трошкови.
        /// </summary>
        internal static string Overview_DailyExpenses {
            get {
                return ResourceManager.GetString("Overview_DailyExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расход.
        /// </summary>
        internal static string Overview_Expense {
            get {
                return ResourceManager.GetString("Overview_Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Филтери.
        /// </summary>
        internal static string Overview_Filters {
            get {
                return ResourceManager.GetString("Overview_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За текући месец.
        /// </summary>
        internal static string Overview_ForMonth {
            get {
                return ResourceManager.GetString("Overview_ForMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За шест месеци.
        /// </summary>
        internal static string Overview_ForSixMonths {
            get {
                return ResourceManager.GetString("Overview_ForSixMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За три месеца.
        /// </summary>
        internal static string Overview_ForThreeMonths {
            get {
                return ResourceManager.GetString("Overview_ForThreeMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приход.
        /// </summary>
        internal static string Overview_Income {
            get {
                return ResourceManager.GetString("Overview_Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приходи и расходи.
        /// </summary>
        internal static string Overview_IncomeExpense {
            get {
                return ResourceManager.GetString("Overview_IncomeExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главни.
        /// </summary>
        internal static string OverView_SpendingType_Main {
            get {
                return ResourceManager.GetString("OverView_SpendingType_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сачувани.
        /// </summary>
        internal static string Overview_SpendingType_Saved {
            get {
                return ResourceManager.GetString("Overview_SpendingType_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Споредни.
        /// </summary>
        internal static string Overview_SpendingType_Secondary {
            get {
                return ResourceManager.GetString("Overview_SpendingType_Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трошкови по типовима.
        /// </summary>
        internal static string Overview_SpendingTypes {
            get {
                return ResourceManager.GetString("Overview_SpendingTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недељни трошкови.
        /// </summary>
        internal static string Overview_WeeklyExpenses {
            get {
                return ResourceManager.GetString("Overview_WeeklyExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Датум до.
        /// </summary>
        internal static string OverviewFilters_EndDate {
            get {
                return ResourceManager.GetString("OverviewFilters_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Датум од.
        /// </summary>
        internal static string OverviewFilters_StartDate {
            get {
                return ResourceManager.GetString("OverviewFilters_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аутентификација.
        /// </summary>
        internal static string Pages_Authentication {
            get {
                return ResourceManager.GetString("Pages_Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категорије.
        /// </summary>
        internal static string Pages_Categories {
            get {
                return ResourceManager.GetString("Pages_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почетна.
        /// </summary>
        internal static string Pages_Home {
            get {
                return ResourceManager.GetString("Pages_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увоз/Извоз.
        /// </summary>
        internal static string Pages_ImportExport {
            get {
                return ResourceManager.GetString("Pages_ImportExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Језик.
        /// </summary>
        internal static string Pages_Language {
            get {
                return ResourceManager.GetString("Pages_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категорија.
        /// </summary>
        internal static string Pages_NewCategory {
            get {
                return ResourceManager.GetString("Pages_NewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трансакција.
        /// </summary>
        internal static string Pages_NewTransaction {
            get {
                return ResourceManager.GetString("Pages_NewTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преглед.
        /// </summary>
        internal static string Pages_Overview {
            get {
                return ResourceManager.GetString("Pages_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Филтери.
        /// </summary>
        internal static string Pages_OverviewFilters {
            get {
                return ResourceManager.GetString("Pages_OverviewFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профили.
        /// </summary>
        internal static string Pages_Profiles {
            get {
                return ResourceManager.GetString("Pages_Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подешавања.
        /// </summary>
        internal static string Pages_Settings {
            get {
                return ResourceManager.GetString("Pages_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема.
        /// </summary>
        internal static string Pages_Theme {
            get {
                return ResourceManager.GetString("Pages_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трансакције.
        /// </summary>
        internal static string Pages_Transactions {
            get {
                return ResourceManager.GetString("Pages_Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Филтери трансакција.
        /// </summary>
        internal static string Pages_TransactionsFilters {
            get {
                return ResourceManager.GetString("Pages_TransactionsFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Откажи.
        /// </summary>
        internal static string ProfileSettings_ChangeAlert_Cancel {
            get {
                return ResourceManager.GetString("ProfileSettings_ChangeAlert_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да ли сте сигурни да желите да поставите профил &quot;{0}&quot; као тренутни?.
        /// </summary>
        internal static string ProfileSettings_ChangeAlert_Desription {
            get {
                return ResourceManager.GetString("ProfileSettings_ChangeAlert_Desription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        internal static string ProfileSettings_ChangeAlert_Ok {
            get {
                return ResourceManager.GetString("ProfileSettings_ChangeAlert_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Промена тренутног профила.
        /// </summary>
        internal static string ProfileSettings_ChangeAlert_Title {
            get {
                return ResourceManager.GetString("ProfileSettings_ChangeAlert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Откажи.
        /// </summary>
        internal static string ProfileSettings_DeleteAlert_Cancel {
            get {
                return ResourceManager.GetString("ProfileSettings_DeleteAlert_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да ли сте сигурни да желите да обришете профил &quot;{0}&quot;? Све трансакције и категорије овог профила ће такође бити обрисане..
        /// </summary>
        internal static string ProfileSettings_DeleteAlert_Description {
            get {
                return ResourceManager.GetString("ProfileSettings_DeleteAlert_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        internal static string ProfileSettings_DeleteAlert_Ok {
            get {
                return ResourceManager.GetString("ProfileSettings_DeleteAlert_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Брисање профила.
        /// </summary>
        internal static string ProfileSettings_DeleteAlert_Title {
            get {
                return ResourceManager.GetString("ProfileSettings_DeleteAlert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профил &quot;{0}&quot; је последњи профил и не може бити обрисан..
        /// </summary>
        internal static string ProfileSettings_LastProfileErrorAlert_Description {
            get {
                return ResourceManager.GetString("ProfileSettings_LastProfileErrorAlert_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У реду.
        /// </summary>
        internal static string ProfileSettings_LastProfileErrorAlert_Ok {
            get {
                return ResourceManager.GetString("ProfileSettings_LastProfileErrorAlert_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последњи профил.
        /// </summary>
        internal static string ProfileSettings_LastProfileErrorAlert_Title {
            get {
                return ResourceManager.GetString("ProfileSettings_LastProfileErrorAlert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Годишње.
        /// </summary>
        internal static string RecurringTransactionInterval_Annually {
            get {
                return ResourceManager.GetString("RecurringTransactionInterval_Annually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дневно.
        /// </summary>
        internal static string RecurringTransactionInterval_Daily {
            get {
                return ResourceManager.GetString("RecurringTransactionInterval_Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сваких шест месеци.
        /// </summary>
        internal static string RecurringTransactionInterval_EverySixMonths {
            get {
                return ResourceManager.GetString("RecurringTransactionInterval_EverySixMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Месечно.
        /// </summary>
        internal static string RecurringTransactionInterval_Monthly {
            get {
                return ResourceManager.GetString("RecurringTransactionInterval_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ниједан.
        /// </summary>
        internal static string RecurringTransactionInterval_None {
            get {
                return ResourceManager.GetString("RecurringTransactionInterval_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to квартално.
        /// </summary>
        internal static string RecurringTransactionInterval_Quarterly {
            get {
                return ResourceManager.GetString("RecurringTransactionInterval_Quarterly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недељно.
        /// </summary>
        internal static string RecurringTransactionInterval_Weekly {
            get {
                return ResourceManager.GetString("RecurringTransactionInterval_Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} трансакција је креирано у позадини.
        /// </summary>
        internal static string RecurringTransactionWorker_CreateTransactionsForRecurred_Description {
            get {
                return ResourceManager.GetString("RecurringTransactionWorker_CreateTransactionsForRecurred_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Понављајућа трансакција.
        /// </summary>
        internal static string RecurringTransactionWorker_CreateTransactionsForRecurred_Title {
            get {
                return ResourceManager.GetString("RecurringTransactionWorker_CreateTransactionsForRecurred_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О апликацији.
        /// </summary>
        internal static string Settings_AboutApplication {
            get {
                return ResourceManager.GetString("Settings_AboutApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Апликација.
        /// </summary>
        internal static string Settings_Application {
            get {
                return ResourceManager.GetString("Settings_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аутентификација.
        /// </summary>
        internal static string Settings_Authentication {
            get {
                return ResourceManager.GetString("Settings_Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категорије.
        /// </summary>
        internal static string Settings_Categories {
            get {
                return ResourceManager.GetString("Settings_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опште.
        /// </summary>
        internal static string Settings_General {
            get {
                return ResourceManager.GetString("Settings_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        internal static string Settings_GitHub {
            get {
                return ResourceManager.GetString("Settings_GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увоз/Извоз.
        /// </summary>
        internal static string Settings_ImportExport {
            get {
                return ResourceManager.GetString("Settings_ImportExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Језик.
        /// </summary>
        internal static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профили.
        /// </summary>
        internal static string Settings_Profiles {
            get {
                return ResourceManager.GetString("Settings_Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оцените апликацију.
        /// </summary>
        internal static string Settings_RateTheApp {
            get {
                return ResourceManager.GetString("Settings_RateTheApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема.
        /// </summary>
        internal static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Верзија.
        /// </summary>
        internal static string Settings_Version {
            get {
                return ResourceManager.GetString("Settings_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Датум од.
        /// </summary>
        internal static string StartNewPeriod_DateFrom {
            get {
                return ResourceManager.GetString("StartNewPeriod_DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Датум до.
        /// </summary>
        internal static string StartNewPeriod_DateTo {
            get {
                return ResourceManager.GetString("StartNewPeriod_DateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нови период.
        /// </summary>
        internal static string StartNewPeriod_NewPeriod {
            get {
                return ResourceManager.GetString("StartNewPeriod_NewPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почни нови период.
        /// </summary>
        internal static string StartNewPeriod_StartNewPeriod {
            get {
                return ResourceManager.GetString("StartNewPeriod_StartNewPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тамна.
        /// </summary>
        internal static string ThemeSettings_Dark {
            get {
                return ResourceManager.GetString("ThemeSettings_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Светла.
        /// </summary>
        internal static string ThemeSettings_LightTheme {
            get {
                return ResourceManager.GetString("ThemeSettings_LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Системска.
        /// </summary>
        internal static string ThemeSettings_System {
            get {
                return ResourceManager.GetString("ThemeSettings_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Откажи.
        /// </summary>
        internal static string Transactions_DeleteAlert_Cancel {
            get {
                return ResourceManager.GetString("Transactions_DeleteAlert_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да ли сте сигурни да желите да обришете трансакцију &quot;{0}&quot;?.
        /// </summary>
        internal static string Transactions_DeleteAlert_Description {
            get {
                return ResourceManager.GetString("Transactions_DeleteAlert_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        internal static string Transactions_DeleteAlert_Ok {
            get {
                return ResourceManager.GetString("Transactions_DeleteAlert_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Брисање трансакције.
        /// </summary>
        internal static string Transactions_DeleteAlert_Title {
            get {
                return ResourceManager.GetString("Transactions_DeleteAlert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Откажи.
        /// </summary>
        internal static string Transactions_EditNotInPeriodAlert_Cancel {
            get {
                return ResourceManager.GetString("Transactions_EditNotInPeriodAlert_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да ли сте сигурни да желите да измените трансакцију &quot;{0}&quot;? Она није у тренутном периоду профила и не утиче на израчунавање профила..
        /// </summary>
        internal static string Transactions_EditNotInPeriodAlert_Description {
            get {
                return ResourceManager.GetString("Transactions_EditNotInPeriodAlert_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        internal static string Transactions_EditNotInPeriodAlert_Ok {
            get {
                return ResourceManager.GetString("Transactions_EditNotInPeriodAlert_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трансакција није у периоду профила.
        /// </summary>
        internal static string Transactions_EditNotInPeriodAlert_Title {
            get {
                return ResourceManager.GetString("Transactions_EditNotInPeriodAlert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расход.
        /// </summary>
        internal static string Transactions_Expense {
            get {
                return ResourceManager.GetString("Transactions_Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Филтери.
        /// </summary>
        internal static string Transactions_Filters {
            get {
                return ResourceManager.GetString("Transactions_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приход.
        /// </summary>
        internal static string Transactions_Income {
            get {
                return ResourceManager.GetString("Transactions_Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главни.
        /// </summary>
        internal static string Transactions_Main {
            get {
                return ResourceManager.GetString("Transactions_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Није пронађена ниједна трансакција за наведене филтере.
        /// </summary>
        internal static string Transactions_NoTransactions {
            get {
                return ResourceManager.GetString("Transactions_NoTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сачувани.
        /// </summary>
        internal static string Transactions_Saved {
            get {
                return ResourceManager.GetString("Transactions_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Споредни.
        /// </summary>
        internal static string Transactions_Secondary {
            get {
                return ResourceManager.GetString("Transactions_Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Износ.
        /// </summary>
        internal static string TransactionsFilters_AmountToSearch {
            get {
                return ResourceManager.GetString("TransactionsFilters_AmountToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Примени филтере.
        /// </summary>
        internal static string TransactionsFilters_ApplyFilters {
            get {
                return ResourceManager.GetString("TransactionsFilters_ApplyFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категорија.
        /// </summary>
        internal static string TransactionsFilters_Category {
            get {
                return ResourceManager.GetString("TransactionsFilters_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Валута.
        /// </summary>
        internal static string TransactionsFilters_Currency {
            get {
                return ResourceManager.GetString("TransactionsFilters_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опис.
        /// </summary>
        internal static string TransactionsFilters_Description {
            get {
                return ResourceManager.GetString("TransactionsFilters_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Датум до.
        /// </summary>
        internal static string TransactionsFilters_EndDate {
            get {
                return ResourceManager.GetString("TransactionsFilters_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Више од.
        /// </summary>
        internal static string TransactionsFilters_GreaterThan {
            get {
                return ResourceManager.GetString("TransactionsFilters_GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мање од.
        /// </summary>
        internal static string TransactionsFilters_LessThan {
            get {
                return ResourceManager.GetString("TransactionsFilters_LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Било који.
        /// </summary>
        internal static string TransactionsFilters_Pickers_Any {
            get {
                return ResourceManager.GetString("TransactionsFilters_Pickers_Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Интервал понављајућих трансакција.
        /// </summary>
        internal static string TransactionsFilters_RecurringTransactionInterval {
            get {
                return ResourceManager.GetString("TransactionsFilters_RecurringTransactionInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Било који.
        /// </summary>
        internal static string TransactionsFilters_RecurringTransactionInterval_Any {
            get {
                return ResourceManager.GetString("TransactionsFilters_RecurringTransactionInterval_Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ресетуј филтере.
        /// </summary>
        internal static string TransactionsFilters_ResetFilters {
            get {
                return ResourceManager.GetString("TransactionsFilters_ResetFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Претрага по износу.
        /// </summary>
        internal static string TransactionsFilters_SearchByAmount {
            get {
                return ResourceManager.GetString("TransactionsFilters_SearchByAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Претрага по валути.
        /// </summary>
        internal static string TransactionsFilters_SearchByCurrency {
            get {
                return ResourceManager.GetString("TransactionsFilters_SearchByCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип трошка.
        /// </summary>
        internal static string TransactionsFilters_SpendingType {
            get {
                return ResourceManager.GetString("TransactionsFilters_SpendingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Датум од.
        /// </summary>
        internal static string TransactionsFilters_StartDate {
            get {
                return ResourceManager.GetString("TransactionsFilters_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип трансакције.
        /// </summary>
        internal static string TransactionsFilters_TransactionType {
            get {
                return ResourceManager.GetString("TransactionsFilters_TransactionType", resourceCulture);
            }
        }
    }
}
