//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profitocracy.Mobile.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Profitocracy.Mobile.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name.
        /// </summary>
        internal static string AddCategory_CategoryName {
            get {
                return ResourceManager.GetString("AddCategory_CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned amount.
        /// </summary>
        internal static string AddCategory_PlannedAmount {
            get {
                return ResourceManager.GetString("AddCategory_PlannedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save category.
        /// </summary>
        internal static string AddCategory_SaveCategory {
            get {
                return ResourceManager.GetString("AddCategory_SaveCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify planned amount.
        /// </summary>
        internal static string AddCategory_SpecifyPlannedAmount {
            get {
                return ResourceManager.GetString("AddCategory_SpecifyPlannedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount in main currency.
        /// </summary>
        internal static string AddTransaction_Amount {
            get {
                return ResourceManager.GetString("AddTransaction_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string AddTransaction_Category {
            get {
                return ResourceManager.GetString("AddTransaction_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string AddTransaction_Date {
            get {
                return ResourceManager.GetString("AddTransaction_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string AddTransaction_Description {
            get {
                return ResourceManager.GetString("AddTransaction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense.
        /// </summary>
        internal static string AddTransaction_Expense {
            get {
                return ResourceManager.GetString("AddTransaction_Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        internal static string AddTransaction_Income {
            get {
                return ResourceManager.GetString("AddTransaction_Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string AddTransaction_Main {
            get {
                return ResourceManager.GetString("AddTransaction_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multicurrency Transaction.
        /// </summary>
        internal static string AddTransaction_MultiCurrencyTransaction {
            get {
                return ResourceManager.GetString("AddTransaction_MultiCurrencyTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string AddTransaction_NoneCategory {
            get {
                return ResourceManager.GetString("AddTransaction_NoneCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount in the original currency.
        /// </summary>
        internal static string AddTransaction_OriginalCurrencyAmount {
            get {
                return ResourceManager.GetString("AddTransaction_OriginalCurrencyAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        internal static string AddTransaction_Saved {
            get {
                return ResourceManager.GetString("AddTransaction_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save transaction.
        /// </summary>
        internal static string AddTransaction_SaveTransaction {
            get {
                return ResourceManager.GetString("AddTransaction_SaveTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary.
        /// </summary>
        internal static string AddTransaction_Secondary {
            get {
                return ResourceManager.GetString("AddTransaction_Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount to withdraw.
        /// </summary>
        internal static string AddTransaction_WithdrawAmount {
            get {
                return ResourceManager.GetString("AddTransaction_WithdrawAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw from Saved Funds.
        /// </summary>
        internal static string AddTransaction_WithdrawSavedFunds {
            get {
                return ResourceManager.GetString("AddTransaction_WithdrawSavedFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No limits.
        /// </summary>
        internal static string Categories_NoLimits {
            get {
                return ResourceManager.GetString("Categories_NoLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CategoriesSettings_DeleteAlert_Cancel {
            get {
                return ResourceManager.GetString("CategoriesSettings_DeleteAlert_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete category &quot;{0}&quot;?.
        /// </summary>
        internal static string CategoriesSettings_DeleteAlert_Description {
            get {
                return ResourceManager.GetString("CategoriesSettings_DeleteAlert_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string CategoriesSettings_DeleteAlert_Ok {
            get {
                return ResourceManager.GetString("CategoriesSettings_DeleteAlert_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Category.
        /// </summary>
        internal static string CategoriesSettings_DeleteAlert_Title {
            get {
                return ResourceManager.GetString("CategoriesSettings_DeleteAlert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount must be a number.
        /// </summary>
        internal static string CommonError_AmountNumber {
            get {
                return ResourceManager.GetString("CommonError_AmountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance must be a number.
        /// </summary>
        internal static string CommonError_BalanceNumber {
            get {
                return ResourceManager.GetString("CommonError_BalanceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find category to delete.
        /// </summary>
        internal static string CommonError_FindCategoryToDelete {
            get {
                return ResourceManager.GetString("CommonError_FindCategoryToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find category to edit.
        /// </summary>
        internal static string CommonError_FindCategoryToEdit {
            get {
                return ResourceManager.GetString("CommonError_FindCategoryToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find transaction to delete.
        /// </summary>
        internal static string CommonError_FindTransactionToDelete {
            get {
                return ResourceManager.GetString("CommonError_FindTransactionToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find transaction to edit.
        /// </summary>
        internal static string CommonError_FindTransactionToEdit {
            get {
                return ResourceManager.GetString("CommonError_FindTransactionToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get category info.
        /// </summary>
        internal static string CommonError_GetCategoryInfo {
            get {
                return ResourceManager.GetString("CommonError_GetCategoryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get current profile.
        /// </summary>
        internal static string CommonError_GetCurrentProfile {
            get {
                return ResourceManager.GetString("CommonError_GetCurrentProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find profile with specified ID.
        /// </summary>
        internal static string CommonError_GetProfileById {
            get {
                return ResourceManager.GetString("CommonError_GetProfileById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find settings.
        /// </summary>
        internal static string CommonError_GetSettings {
            get {
                return ResourceManager.GetString("CommonError_GetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error occurred. Try again.
        /// </summary>
        internal static string CommonError_InternalErrorTryAgain {
            get {
                return ResourceManager.GetString("CommonError_InternalErrorTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open category adding page.
        /// </summary>
        internal static string CommonError_OpenAddCategoryPage {
            get {
                return ResourceManager.GetString("CommonError_OpenAddCategoryPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open transaction edit page.
        /// </summary>
        internal static string CommonError_OpenEditTransactionPage {
            get {
                return ResourceManager.GetString("CommonError_OpenEditTransactionPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open transactions filters page.
        /// </summary>
        internal static string CommonError_OpenTransactionsFiltersPage {
            get {
                return ResourceManager.GetString("CommonError_OpenTransactionsFiltersPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount in original currency must be a number.
        /// </summary>
        internal static string CommonError_OriginalCurrencyAmountNumber {
            get {
                return ResourceManager.GetString("CommonError_OriginalCurrencyAmountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned amount must be a number.
        /// </summary>
        internal static string CommonError_PlannedAmountNumber {
            get {
                return ResourceManager.GetString("CommonError_PlannedAmountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot show filtered transactions.
        /// </summary>
        internal static string CommonError_ShowFilteredTransactions {
            get {
                return ResourceManager.GetString("CommonError_ShowFilteredTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid transaction type.
        /// </summary>
        internal static string CommonError_TransactionType {
            get {
                return ResourceManager.GetString("CommonError_TransactionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UAE Dirham.
        /// </summary>
        internal static string Currencies_AED {
            get {
                return ResourceManager.GetString("Currencies_AED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argentine Peso.
        /// </summary>
        internal static string Currencies_ARS {
            get {
                return ResourceManager.GetString("Currencies_ARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australian Dollar.
        /// </summary>
        internal static string Currencies_AUD {
            get {
                return ResourceManager.GetString("Currencies_AUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bangladeshi Taka.
        /// </summary>
        internal static string Currencies_BDT {
            get {
                return ResourceManager.GetString("Currencies_BDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgarian Lev.
        /// </summary>
        internal static string Currencies_BGN {
            get {
                return ResourceManager.GetString("Currencies_BGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brazilian Real.
        /// </summary>
        internal static string Currencies_BRL {
            get {
                return ResourceManager.GetString("Currencies_BRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitcoin.
        /// </summary>
        internal static string Currencies_BTC {
            get {
                return ResourceManager.GetString("Currencies_BTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canadian Dollar.
        /// </summary>
        internal static string Currencies_CAD {
            get {
                return ResourceManager.GetString("Currencies_CAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swiss Franc.
        /// </summary>
        internal static string Currencies_CHF {
            get {
                return ResourceManager.GetString("Currencies_CHF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chilean Peso.
        /// </summary>
        internal static string Currencies_CLP {
            get {
                return ResourceManager.GetString("Currencies_CLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Yuan.
        /// </summary>
        internal static string Currencies_CNY {
            get {
                return ResourceManager.GetString("Currencies_CNY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colombian Peso.
        /// </summary>
        internal static string Currencies_COP {
            get {
                return ResourceManager.GetString("Currencies_COP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech Koruna.
        /// </summary>
        internal static string Currencies_CZK {
            get {
                return ResourceManager.GetString("Currencies_CZK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danish Krone.
        /// </summary>
        internal static string Currencies_DKK {
            get {
                return ResourceManager.GetString("Currencies_DKK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egyptian Pound.
        /// </summary>
        internal static string Currencies_EGP {
            get {
                return ResourceManager.GetString("Currencies_EGP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ether.
        /// </summary>
        internal static string Currencies_ETH {
            get {
                return ResourceManager.GetString("Currencies_ETH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euro.
        /// </summary>
        internal static string Currencies_EUR {
            get {
                return ResourceManager.GetString("Currencies_EUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiji Dollar.
        /// </summary>
        internal static string Currencies_FJD {
            get {
                return ResourceManager.GetString("Currencies_FJD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to British Pound.
        /// </summary>
        internal static string Currencies_GBP {
            get {
                return ResourceManager.GetString("Currencies_GBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghanaian Cedi.
        /// </summary>
        internal static string Currencies_GHS {
            get {
                return ResourceManager.GetString("Currencies_GHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hong Kong Dollar.
        /// </summary>
        internal static string Currencies_HKD {
            get {
                return ResourceManager.GetString("Currencies_HKD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungarian Forint.
        /// </summary>
        internal static string Currencies_HUF {
            get {
                return ResourceManager.GetString("Currencies_HUF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indonesian Rupiah.
        /// </summary>
        internal static string Currencies_IDR {
            get {
                return ResourceManager.GetString("Currencies_IDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Israeli New Shekel.
        /// </summary>
        internal static string Currencies_ILS {
            get {
                return ResourceManager.GetString("Currencies_ILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indian Rupee.
        /// </summary>
        internal static string Currencies_INR {
            get {
                return ResourceManager.GetString("Currencies_INR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iraqi Dinar.
        /// </summary>
        internal static string Currencies_IQD {
            get {
                return ResourceManager.GetString("Currencies_IQD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese Yen.
        /// </summary>
        internal static string Currencies_JPY {
            get {
                return ResourceManager.GetString("Currencies_JPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kenyan Shilling.
        /// </summary>
        internal static string Currencies_KES {
            get {
                return ResourceManager.GetString("Currencies_KES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Korean Won.
        /// </summary>
        internal static string Currencies_KRW {
            get {
                return ResourceManager.GetString("Currencies_KRW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuwaiti Dinar.
        /// </summary>
        internal static string Currencies_KWD {
            get {
                return ResourceManager.GetString("Currencies_KWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mexican Peso.
        /// </summary>
        internal static string Currencies_MXN {
            get {
                return ResourceManager.GetString("Currencies_MXN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malaysian Ringgit.
        /// </summary>
        internal static string Currencies_MYR {
            get {
                return ResourceManager.GetString("Currencies_MYR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nigerian Naira.
        /// </summary>
        internal static string Currencies_NGN {
            get {
                return ResourceManager.GetString("Currencies_NGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norwegian Krone.
        /// </summary>
        internal static string Currencies_NOK {
            get {
                return ResourceManager.GetString("Currencies_NOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Zealand Dollar.
        /// </summary>
        internal static string Currencies_NZD {
            get {
                return ResourceManager.GetString("Currencies_NZD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omani Rial.
        /// </summary>
        internal static string Currencies_OMR {
            get {
                return ResourceManager.GetString("Currencies_OMR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Philippine Peso.
        /// </summary>
        internal static string Currencies_PHP {
            get {
                return ResourceManager.GetString("Currencies_PHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pakistani Rupee.
        /// </summary>
        internal static string Currencies_PKR {
            get {
                return ResourceManager.GetString("Currencies_PKR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish Zloty.
        /// </summary>
        internal static string Currencies_PLN {
            get {
                return ResourceManager.GetString("Currencies_PLN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paraguayan Guarani.
        /// </summary>
        internal static string Currencies_PYG {
            get {
                return ResourceManager.GetString("Currencies_PYG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romanian Leu.
        /// </summary>
        internal static string Currencies_RON {
            get {
                return ResourceManager.GetString("Currencies_RON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbian Dinar.
        /// </summary>
        internal static string Currencies_RSD {
            get {
                return ResourceManager.GetString("Currencies_RSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian Ruble.
        /// </summary>
        internal static string Currencies_RUB {
            get {
                return ResourceManager.GetString("Currencies_RUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saudi Riyal.
        /// </summary>
        internal static string Currencies_SAR {
            get {
                return ResourceManager.GetString("Currencies_SAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedish Krona.
        /// </summary>
        internal static string Currencies_SEK {
            get {
                return ResourceManager.GetString("Currencies_SEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singapore Dollar.
        /// </summary>
        internal static string Currencies_SGD {
            get {
                return ResourceManager.GetString("Currencies_SGD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thai Baht.
        /// </summary>
        internal static string Currencies_THB {
            get {
                return ResourceManager.GetString("Currencies_THB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish Lira.
        /// </summary>
        internal static string Currencies_TRY {
            get {
                return ResourceManager.GetString("Currencies_TRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taiwan Dollar.
        /// </summary>
        internal static string Currencies_TWD {
            get {
                return ResourceManager.GetString("Currencies_TWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United States Dollar.
        /// </summary>
        internal static string Currencies_USD {
            get {
                return ResourceManager.GetString("Currencies_USD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venezuelan Bolívar.
        /// </summary>
        internal static string Currencies_VEF {
            get {
                return ResourceManager.GetString("Currencies_VEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnamese Dong.
        /// </summary>
        internal static string Currencies_VND {
            get {
                return ResourceManager.GetString("Currencies_VND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samoan Tala.
        /// </summary>
        internal static string Currencies_WST {
            get {
                return ResourceManager.GetString("Currencies_WST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South African Rand.
        /// </summary>
        internal static string Currencies_ZAR {
            get {
                return ResourceManager.GetString("Currencies_ZAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial balance.
        /// </summary>
        internal static string EditProfile_InitialBalance {
            get {
                return ResourceManager.GetString("EditProfile_InitialBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string EditProfile_Profile {
            get {
                return ResourceManager.GetString("EditProfile_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile name.
        /// </summary>
        internal static string EditProfile_ProfileName {
            get {
                return ResourceManager.GetString("EditProfile_ProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save profile.
        /// </summary>
        internal static string EditProfile_SaveProfile {
            get {
                return ResourceManager.GetString("EditProfile_SaveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        internal static string ErrorAlert_Description {
            get {
                return ResourceManager.GetString("ErrorAlert_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ErrorAlert_Ok {
            get {
                return ResourceManager.GetString("ErrorAlert_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorAlert_Title {
            get {
                return ResourceManager.GetString("ErrorAlert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string Home_Balance {
            get {
                return ResourceManager.GetString("Home_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories expenses.
        /// </summary>
        internal static string Home_Categories {
            get {
                return ResourceManager.GetString("Home_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily amounts.
        /// </summary>
        internal static string Home_DailyAmounts {
            get {
                return ResourceManager.GetString("Home_DailyAmounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string Home_Main {
            get {
                return ResourceManager.GetString("Home_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no categories.
        /// </summary>
        internal static string Home_NoCategories {
            get {
                return ResourceManager.GetString("Home_NoCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        internal static string Home_Saved {
            get {
                return ResourceManager.GetString("Home_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Amounts.
        /// </summary>
        internal static string Home_SavedAmounts {
            get {
                return ResourceManager.GetString("Home_SavedAmounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary.
        /// </summary>
        internal static string Home_Secondary {
            get {
                return ResourceManager.GetString("Home_Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spending types.
        /// </summary>
        internal static string Home_SpendingTypes {
            get {
                return ResourceManager.GetString("Home_SpendingTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string Home_TodayBalance {
            get {
                return ResourceManager.GetString("Home_TodayBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        internal static string Home_TomorrowBalance {
            get {
                return ResourceManager.GetString("Home_TomorrowBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To make the changes take effect, you need to restart the application..
        /// </summary>
        internal static string InfoAlert_ChangeLanguage_Message {
            get {
                return ResourceManager.GetString("InfoAlert_ChangeLanguage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string InfoAlert_ChangeLanguage_Ok {
            get {
                return ResourceManager.GetString("InfoAlert_ChangeLanguage_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string InfoAlert_ChangeLanguage_Title {
            get {
                return ResourceManager.GetString("InfoAlert_ChangeLanguage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is not available yet. We will implement it soon.
        /// </summary>
        internal static string InfoAlert_FeatureNotAvailable_Message {
            get {
                return ResourceManager.GetString("InfoAlert_FeatureNotAvailable_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string InfoAlert_FeatureNotAvailable_Ok {
            get {
                return ResourceManager.GetString("InfoAlert_FeatureNotAvailable_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Available Yet.
        /// </summary>
        internal static string InfoAlert_FeatureNotAvailable_Title {
            get {
                return ResourceManager.GetString("InfoAlert_FeatureNotAvailable_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Languages_English {
            get {
                return ResourceManager.GetString("Languages_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string Languages_French {
            get {
                return ResourceManager.GetString("Languages_French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        internal static string Languages_Russian {
            get {
                return ResourceManager.GetString("Languages_Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses by Category.
        /// </summary>
        internal static string Overview_CategoriesExpenses {
            get {
                return ResourceManager.GetString("Overview_CategoriesExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned and Actual Expenses by Category.
        /// </summary>
        internal static string Overview_CategoriesPlannedAndActual {
            get {
                return ResourceManager.GetString("Overview_CategoriesPlannedAndActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily expenses.
        /// </summary>
        internal static string Overview_DailyExpenses {
            get {
                return ResourceManager.GetString("Overview_DailyExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense.
        /// </summary>
        internal static string Overview_Expense {
            get {
                return ResourceManager.GetString("Overview_Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the current month.
        /// </summary>
        internal static string Overview_ForMonth {
            get {
                return ResourceManager.GetString("Overview_ForMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For six months.
        /// </summary>
        internal static string Overview_ForSixMonths {
            get {
                return ResourceManager.GetString("Overview_ForSixMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For three months.
        /// </summary>
        internal static string Overview_ForThreeMonths {
            get {
                return ResourceManager.GetString("Overview_ForThreeMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        internal static string Overview_Income {
            get {
                return ResourceManager.GetString("Overview_Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income and Expenses.
        /// </summary>
        internal static string Overview_IncomeExpense {
            get {
                return ResourceManager.GetString("Overview_IncomeExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string OverView_SpendingType_Main {
            get {
                return ResourceManager.GetString("OverView_SpendingType_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        internal static string Overview_SpendingType_Saved {
            get {
                return ResourceManager.GetString("Overview_SpendingType_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary.
        /// </summary>
        internal static string Overview_SpendingType_Secondary {
            get {
                return ResourceManager.GetString("Overview_SpendingType_Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spending Types Expenses.
        /// </summary>
        internal static string Overview_SpendingTypes {
            get {
                return ResourceManager.GetString("Overview_SpendingTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Expenses.
        /// </summary>
        internal static string Overview_WeeklyExpenses {
            get {
                return ResourceManager.GetString("Overview_WeeklyExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string Pages_Categories {
            get {
                return ResourceManager.GetString("Pages_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Pages_Home {
            get {
                return ResourceManager.GetString("Pages_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Pages_Language {
            get {
                return ResourceManager.GetString("Pages_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Pages_NewCategory {
            get {
                return ResourceManager.GetString("Pages_NewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        internal static string Pages_NewTransaction {
            get {
                return ResourceManager.GetString("Pages_NewTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string Pages_Overview {
            get {
                return ResourceManager.GetString("Pages_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        internal static string Pages_Profiles {
            get {
                return ResourceManager.GetString("Pages_Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Pages_Settings {
            get {
                return ResourceManager.GetString("Pages_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Pages_Theme {
            get {
                return ResourceManager.GetString("Pages_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        internal static string Pages_Transactions {
            get {
                return ResourceManager.GetString("Pages_Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions Filters.
        /// </summary>
        internal static string Pages_TransactionsFilters {
            get {
                return ResourceManager.GetString("Pages_TransactionsFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ProfileSettings_ChangeAlert_Cancel {
            get {
                return ResourceManager.GetString("ProfileSettings_ChangeAlert_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to set profile &quot;{0}&quot; current?.
        /// </summary>
        internal static string ProfileSettings_ChangeAlert_Desription {
            get {
                return ResourceManager.GetString("ProfileSettings_ChangeAlert_Desription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ProfileSettings_ChangeAlert_Ok {
            get {
                return ResourceManager.GetString("ProfileSettings_ChangeAlert_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Current Profile.
        /// </summary>
        internal static string ProfileSettings_ChangeAlert_Title {
            get {
                return ResourceManager.GetString("ProfileSettings_ChangeAlert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ProfileSettings_DeleteAlert_Cancel {
            get {
                return ResourceManager.GetString("ProfileSettings_DeleteAlert_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete profile &quot;{0}&quot;? All the profile&apos;s categories and transactions will be deleted too..
        /// </summary>
        internal static string ProfileSettings_DeleteAlert_Description {
            get {
                return ResourceManager.GetString("ProfileSettings_DeleteAlert_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ProfileSettings_DeleteAlert_Ok {
            get {
                return ResourceManager.GetString("ProfileSettings_DeleteAlert_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Profile.
        /// </summary>
        internal static string ProfileSettings_DeleteAlert_Title {
            get {
                return ResourceManager.GetString("ProfileSettings_DeleteAlert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile &quot;{0}&quot; is the last profile and you cannot delete it..
        /// </summary>
        internal static string ProfileSettings_LastProfileErrorAlert_Description {
            get {
                return ResourceManager.GetString("ProfileSettings_LastProfileErrorAlert_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ProfileSettings_LastProfileErrorAlert_Ok {
            get {
                return ResourceManager.GetString("ProfileSettings_LastProfileErrorAlert_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Profile.
        /// </summary>
        internal static string ProfileSettings_LastProfileErrorAlert_Title {
            get {
                return ResourceManager.GetString("ProfileSettings_LastProfileErrorAlert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Settings_AboutApplication {
            get {
                return ResourceManager.GetString("Settings_AboutApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string Settings_Application {
            get {
                return ResourceManager.GetString("Settings_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string Settings_Categories {
            get {
                return ResourceManager.GetString("Settings_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string Settings_General {
            get {
                return ResourceManager.GetString("Settings_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        internal static string Settings_GitHub {
            get {
                return ResourceManager.GetString("Settings_GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        internal static string Settings_Profiles {
            get {
                return ResourceManager.GetString("Settings_Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Settings_Version {
            get {
                return ResourceManager.GetString("Settings_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string ThemeSettings_Dark {
            get {
                return ResourceManager.GetString("ThemeSettings_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string ThemeSettings_LightTheme {
            get {
                return ResourceManager.GetString("ThemeSettings_LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string ThemeSettings_System {
            get {
                return ResourceManager.GetString("ThemeSettings_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Transactions_DeleteAlert_Cancel {
            get {
                return ResourceManager.GetString("Transactions_DeleteAlert_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete transaction &quot;{0}&quot;?.
        /// </summary>
        internal static string Transactions_DeleteAlert_Description {
            get {
                return ResourceManager.GetString("Transactions_DeleteAlert_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Transactions_DeleteAlert_Ok {
            get {
                return ResourceManager.GetString("Transactions_DeleteAlert_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Transaction.
        /// </summary>
        internal static string Transactions_DeleteAlert_Title {
            get {
                return ResourceManager.GetString("Transactions_DeleteAlert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Transactions_EditNotInPeriodAlert_Cancel {
            get {
                return ResourceManager.GetString("Transactions_EditNotInPeriodAlert_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to edit transaction &quot;{0}&quot;? It is not in the current profile period and does not affect on profile calculation..
        /// </summary>
        internal static string Transactions_EditNotInPeriodAlert_Description {
            get {
                return ResourceManager.GetString("Transactions_EditNotInPeriodAlert_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Transactions_EditNotInPeriodAlert_Ok {
            get {
                return ResourceManager.GetString("Transactions_EditNotInPeriodAlert_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction is not in Profile Period.
        /// </summary>
        internal static string Transactions_EditNotInPeriodAlert_Title {
            get {
                return ResourceManager.GetString("Transactions_EditNotInPeriodAlert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense.
        /// </summary>
        internal static string Transactions_Expense {
            get {
                return ResourceManager.GetString("Transactions_Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        internal static string Transactions_Filters {
            get {
                return ResourceManager.GetString("Transactions_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        internal static string Transactions_Income {
            get {
                return ResourceManager.GetString("Transactions_Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string Transactions_Main {
            get {
                return ResourceManager.GetString("Transactions_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        internal static string Transactions_Saved {
            get {
                return ResourceManager.GetString("Transactions_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary.
        /// </summary>
        internal static string Transactions_Secondary {
            get {
                return ResourceManager.GetString("Transactions_Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string TransactionsFilters_AmountToSearch {
            get {
                return ResourceManager.GetString("TransactionsFilters_AmountToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Filters.
        /// </summary>
        internal static string TransactionsFilters_ApplyFilters {
            get {
                return ResourceManager.GetString("TransactionsFilters_ApplyFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string TransactionsFilters_Category {
            get {
                return ResourceManager.GetString("TransactionsFilters_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string TransactionsFilters_Currency {
            get {
                return ResourceManager.GetString("TransactionsFilters_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string TransactionsFilters_Description {
            get {
                return ResourceManager.GetString("TransactionsFilters_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date to.
        /// </summary>
        internal static string TransactionsFilters_EndDate {
            get {
                return ResourceManager.GetString("TransactionsFilters_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater than.
        /// </summary>
        internal static string TransactionsFilters_GreaterThan {
            get {
                return ResourceManager.GetString("TransactionsFilters_GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than.
        /// </summary>
        internal static string TransactionsFilters_LessThan {
            get {
                return ResourceManager.GetString("TransactionsFilters_LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        internal static string TransactionsFilters_Pickers_Any {
            get {
                return ResourceManager.GetString("TransactionsFilters_Pickers_Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset filters.
        /// </summary>
        internal static string TransactionsFilters_ResetFilters {
            get {
                return ResourceManager.GetString("TransactionsFilters_ResetFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by amount.
        /// </summary>
        internal static string TransactionsFilters_SearchByAmount {
            get {
                return ResourceManager.GetString("TransactionsFilters_SearchByAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by currency.
        /// </summary>
        internal static string TransactionsFilters_SearchByCurrency {
            get {
                return ResourceManager.GetString("TransactionsFilters_SearchByCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spending type.
        /// </summary>
        internal static string TransactionsFilters_SpendingType {
            get {
                return ResourceManager.GetString("TransactionsFilters_SpendingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date from.
        /// </summary>
        internal static string TransactionsFilters_StartDate {
            get {
                return ResourceManager.GetString("TransactionsFilters_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction type.
        /// </summary>
        internal static string TransactionsFilters_TransactionType {
            get {
                return ResourceManager.GetString("TransactionsFilters_TransactionType", resourceCulture);
            }
        }
    }
}
